### ISSUE TITLE
Auto-registering graph type todo / wish list

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/graphql-dotnet#2893]
- [ ] #2884 
- [ ] #2891 
- [ ] #2892 
- [ ] `[DefaultValueAst]` attribute?
- [ ] `IObservable<T>` support for subscription support for methods
- [ ] Add own `[Description]`, `[DeprecationReason]`  and `[DefaultValue]` attributes?
- [ ] Deprecate `[GraphQLMetadata]` attribute?
- [ ] Add `[IsTypeOf]` attribute
- [ ] Interface support via `AutoRegisteringInterfaceGraphType`
- [ ] Consider attribute namespace and/or file location within repo.
- [ ] Add documentation (not just migration docs) for all new functionality
- [ ] Extend `SchemaTypes` to allow auto-generating input or output types when no mapping is found?
- [ ] Some other way of auto-registering within the service provider the `AutoRegistering...GraphType` classes for the CLR types to be used?  e.g. via an attribute `[AutoRegistering]`?  Or perhaps this is done inside `SchemaTypes`.
- [ ] Consider alternative way of handling lists, so lists inside of lists are supported better within `TypeInformation`.
- [ ] Add demo project to demonstrate new functionality
