### ISSUE TITLE
Update docs for 2.0 milestone

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/graphql-dotnet#440]
- [x] New docs infrastructure
- [x] Schema + Handlers/Endpoints
- [x] Dependency Injection interface
- [x] Migration Guides

**Comment by simonhaenisch** [comment]
- [ ] add a migration guide?

**Comment by RehanSaeed** [comment]
I'm new to GraphQL.NET. Assuming 2.0 is a breaking change and I'm just investigating with no concrete plans to build anything, is it worth looking at the 2.0 alpha builds instead? Is there a guestimate for when it will solidify?

**Comment by joemcbride** [comment]
Mainly just documentation left.  Hope to have everything ready in the next couple weeks.  See the new docs.  https://graphql-dotnet.github.io/

**Comment by joemcbride** [comment]
Calling the docs done for now.
